# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# dist
dist: jammy

# list any PHP version you want to test against
php:
  - 7.1
  - 8.0
  - 8.1
  - 8.2
  
before_script:
  - curl --version
  - composer self-update
  - composer install --no-interaction --prefer-source --dev  
